name: issyosan_factory
description: Factory that creates parts for issyosan app

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  intl:
  font_awesome_flutter:
  image_picker:
  connectivity:
  flutter_local_notifications:
  get_it:
  provider:
  shared_preferences:
  http:
  logging:
  stack_trace:
  state_notifier:
  flutter_state_notifier:
  freezed_annotation:

dev_dependencies:
  pedantic_mono:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/ioncs/ic_launcher.png"

