name: issyosan_factory
description: Factory that creates parts for issyosan app

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.4
  connectivity: ^0.4.8+2
  flutter_local_notifications: ^1.4.0
  get_it: ^4.0.1
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3

dev_dependencies:
  pedantic_mono: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/ioncs/ic_launcher.png"

